name: analyzer

services:
  service:
    container_name: analyzer-service
    build:
      context: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    restart: on-failure
    ports:
      - "8000:8000"
    hostname: analyzer.service
    networks:
      - net

  db:
    container_name: postgres
    image: postgres:12.7
    restart: on-failure
    command: postgres -c 'max_connections=200'
    env_file:
      - .env
    ports:
      - 5432:5432
    hostname: analyzer.database
    networks:
      - net

networks:
  net:
    driver: bridge
